version: '3'
services:
  app:
    container_name: spring-redis
    image: spring-redis:v1
    build: .
    links:
      - redis
    ports:
      - "8080:20112"
  redis:
    container_name: redis
    image: redis
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"
